<a href="https://colab.research.google.com/github/Dhruvi0901/Machine-Learning/blob/main/ML_Practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  PRACTICAL - 2 Data Preprocessing using Pands

In [3]:
print('Hello Google Colab')

Hello Google Colab


In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a = np.array([1,2,3,4])
print(a[1])

2


In [6]:
a = np.array([1,2,3,4])
print(a[0:3])

[1 2 3]


In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#Get Dimension
a.ndim

1

In [11]:
b.ndim

2

In [12]:
#Get Shape
a.shape

(4,)

In [13]:
b.shape

(2, 4)

In [15]:
#reshape
x = np.array([1,2,3,4,5,6])
print(x)

y = x.reshape(2,3)
print(y)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [16]:
#Get Type
a.dtype

dtype('int64')

In [17]:
#Get total size
a.nbytes 

32

In [18]:
#Get size
a.itemsize

8

In [26]:
#split
a = np.arange(4).reshape(2, 2)
print(a, np.hsplit(a, 2))


[[0 1]
 [2 3]] [array([[0],
       [2]]), array([[1],
       [3]])]


In [25]:
#hsplit
a = np.arange(4).reshape(2, 2)
print(a, np.hsplit(a, 2))

[[0 1]
 [2 3]] [array([[0],
       [2]]), array([[1],
       [3]])]


In [27]:
#vsplit
a = np.arange(4).reshape(2, 2)
print(a, np.vsplit(a, 2))

[[0 1]
 [2 3]] [array([[0, 1]]), array([[2, 3]])]


In [29]:
#dsplit
b = np.arange(27).reshape(3, 3, 3)
print(b, np.dsplit(b, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] [array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]


In [31]:
#insert
a = np.array([2,3,4,5,6,7,8])
print(a)
np.insert(a, 0, 1)

[2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
#delete
a = np.array([2,3,4,5,6,7,8])
print(a)
a_del = np.delete(a, 2, 0)
print(a_del)


[2 3 4 5 6 7 8]
[2 3 5 6 7 8]


In [38]:
#append
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#unique
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [40]:
#flip
a = np.arange(4).reshape((2,2))
print(a)
np.flip(a, 0)

[[0 1]
 [2 3]]


array([[2, 3],
       [0, 1]])

In [41]:
#fliplr
A = np.diag([1.,2.,3.])
print(A)
np.fliplr(A)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

In [42]:
#flatten and ravel
a = np.array( [ (1,5,6,8),(2,3,4,1) ] )
print( a.flatten() )
print ( a.ravel() )

[1 5 6 8 2 3 4 1]
[1 5 6 8 2 3 4 1]


In [43]:
#moveaxis
arr = np.zeros((1, 2, 3, 4, 5, 6))
new_arr = np.moveaxis(arr, 0, -1).shape
print (new_arr)

(2, 3, 4, 5, 6, 1)


In [44]:
#rollaxis
arr = np.ones((1, 2, 3, 4))
new_arr = np.rollaxis(arr, 3, 1).shape
print (new_arr)

(1, 4, 2, 3)


In [45]:
#Any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [46]:
#Any other number
np.full((2,2),27)

array([[27, 27],
       [27, 27]])

In [47]:
#fill
a = np.arange(9)
print("a is \n", a)
a.fill(0)
print("\nNow a is :\n", a)

a is 
 [0 1 2 3 4 5 6 7 8]

Now a is :
 [0 0 0 0 0 0 0 0 0]


In [49]:
#rotate
m=np.array([[1,2,3],[4,5,6]])
print(m)
np.rot90(m,2)

[[1 2 3]
 [4 5 6]]


array([[6, 5, 4],
       [3, 2, 1]])